=== Danikileitor/WebCachonda/DAW/primero/LenguajeMarcas/XML/Enunciados_Ejercicios-Espacios_de_nombres/alumnos_profesores.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="asistentes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="profesores">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="profesor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="alumnos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="alumno" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Danikileitor/WebCachonda/DAW/primero/LenguajeMarcas/XML/Enunciados_Ejercicios-Espacios_de_nombres/alumnos_profesores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Enunciado dado una relación de asistentes formada por alumnos y profesores, y cada uno de ellos tiene nombre.
Hay varios alumnos y varios profesores. Definir un nombre de espacio para cada uno de ellos
alumnos_profesores.xml.
Asociarle una definición DTD-->
<asistentes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="alumnos_profesores.xsd" xmlns:P="profesores" xmlns:A="alumnos">
    <profesores>
        <profesor>
            <nombre>Profesor 1</nombre>
        </profesor>
        <profesor>
            <nombre>Profesor 2</nombre>
        </profesor>
    </profesores>
    <alumnos>
        <alumno>
            <nombre>Alumno 1</nombre>
        </alumno>
        <alumno>
            <nombre>Alumno 2</nombre>
        </alumno>
    </alumnos>
</asistentes>
