=== Danikileitor/WebCachonda/DAW/primero/LenguajeMarcas/XML/LibrosEstanterias/LibrosEstanterias.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="lista_libros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="autor" type="xs:string" />
                            <xs:element name="publicacion" type="fechapublicacion" />
                            <xs:element name="edicion" type="fechaedicion" />
                            <xs:element name="estanteria" type="codestanteria" />
                            <xs:element name="fila" type="codfila" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="fechapublicacion">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1600" />
            <xs:maxInclusive value="1999" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="fechaedicion">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1869" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="codestanteria">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="codfila">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="10" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Danikileitor/WebCachonda/DAW/primero/LenguajeMarcas/XML/LibrosEstanterias/LibrosEstanterias.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--EJERCICIO 7. Escribe un Schema XML para el siguiente documento XML.
Ten en cuenta las siguientes restricciones:
• La fecha de publicación debe ser entre el siglo XVII y el siglo XX. 
• La fecha de edición debe ser del siglo XIX o posterior 
• Las estanterías están codificadas de la A a la Z 
• Las filas están numeradas de la 1 a la 10.-->
<lista_libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LibrosEstanterias.xsd">
    <libro>
        <titulo>El Ingenioso Hidalgo Don Quixote de la Mancha</titulo>
        <autor>Miguel de Cervantes Saavedra</autor>
        <publicacion>1605</publicacion>
        <edicion>2009</edicion>
        <estanteria>B</estanteria>
        <fila>7</fila>
    </libro>
    <libro>
        <titulo>El libro del buen amor</titulo>
        <autor>Juan Ruiz Arcipreste de Hita</autor>
        <publicacion>1630</publicacion>
        <edicion>1869</edicion>
        <estanteria>M</estanteria>
        <fila>9</fila>
    </libro>
</lista_libros>
